import sys
import re

file_path = r'd:\CONG_VIIEC\webapp\frontend\src\pages\StudentHomePage.tsx'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    'ChÆ°a báº¯t Ä‘áº§u': 'Chưa bắt đầu',
    'Ä ang há» c': 'Đang học',
    'Ä Ã£ hoÃ\xa0n thÃ\xa0nh': 'Đã hoàn thành',
    'Cáº§n há»— trá»£ thÃªm': 'Cần hỗ trợ thêm',
    'Ä ang phÃ¹ há»£p': 'Đang phù hợp',
    'Sáºµn sÃ\xa0ng nÃ¢ng Ä‘á»™ khÃ³': 'Sẵn sàng nâng độ khó',
    'GhÃ©p áº£nh': 'Ghép ảnh',
    'Má»Ÿ Ã´ Ä‘oÃ¡n hÃ¬nh': 'Mở ô đoán hình',
    'Chá» n Ä‘Ã¡p Ã¡n': 'Chọn đáp án',
    'NhÃ¬n rá»“i chá» n': 'Nhìn rồi chọn',
    'Ná»‘i Ä‘Ãºng': 'Nối đúng',
    'KÃ©o vÃ\xa0 tháº£': 'Kéo và thả',
    'Nghe vÃ\xa0 chá» n': 'Nghe và chọn',
    'Xem rá»“i tráº£ lá» i': 'Xem rồi trả lời',
    'LÃ\xa0m tá»«ng bÆ°á»›c': 'Làm từng bước',
    'Chá» n tháº»': 'Chọn thẻ',
    'TÃ¬nh huá»‘ng': 'Tình huống',
    'TrÃ² chuyá»‡n': 'Trò chuyện',

    'BÃ\xa0i há» c': 'Bài học',
    'bÃ\xa0i há» c': 'bài học',
    'MÃ\xa0n hÃ¬nh': 'Màn hình',
    'KhÃ´ng gian há» c trá»±c quan': 'Không gian học trực quan',
    'trá»±c quan': 'trực quan',
    'HÃ´m nay mÃ¬nh há» c bÃ\xa0i nÃ\xa0o?': 'Hôm nay mình học bài nào?',
    'MÃ\xa0n hÃ¬nh nÃ\xa0y Ä‘Æ°á»£c lÃ\xa0m theo kiá»ƒu cuá»™n dá» c 100%, nÃºt to vÃ\xa0 tháº» lá»›n Ä‘á»ƒ em chá»‰ viá»‡c nhÃ¬n, cháº¡m vÃ\xa0 kÃ©o xuá»‘ng tiáº¿p tá»¥c tá»«ng bÆ°á»›c.': 'Màn hình này được làm theo kiểu cuộn dọc 100%, nút to và thẻ lớn để em chỉ việc nhìn, chạm và kéo xuống tiếp tục từng bước.',
    'bÃ\xa0i trá»±c quan': 'bài trực quan',
    'bÃ\xa0i Ä‘Ã£ xong': 'bài đã xong',
    'giÃ¡o viÃªn': 'giáo viên',
    'GiÃ¡o viÃªn': 'Giáo viên',

    'HoÃ\xa0n thÃ\xa0nh rá»“i': 'Hoàn thành rồi',
    'Giá» i láº¯m. Em Ä‘Ã£ xong bÃ\xa0i nÃ\xa0y vÃ\xa0 cÃ³ thá»ƒ kÃ©o xuá»‘ng Ä‘á»ƒ chá» n bÃ\xa0i tiáº¿p theo.': 'Giỏi lắm. Em đã xong bài này và có thể kéo xuống để chọn bài tiếp theo.',
    'Chá» n bÃ\xa0i': 'Chọn bài',
    'BÃ\xa0i cá»§a em': 'Bài của em',
    'Cháº¡m vÃ\xa0o tháº» lá»›n bÃªn dÆ°á»›i Ä‘á»ƒ má»Ÿ Ä‘Ãºng bÃ\xa0i giÃ¡o viÃªn Ä‘Ã£ giao.': 'Chạm vào thẻ lớn bên dưới để mở đúng bài giáo viên đã giao.',
    'bÃ\xa0i': 'bài',
    'BÃ\xa0i': 'Bài',

    'BÃ\xa0i táº\xadp #': 'Bài tập #',
    'bÃ\xa0i táº\xadp': 'bài tập',
    'BÃ\xa0i táº\xadp': 'Bài tập',
    'Ä iá»ƒm': 'Điểm',
    'ChÆ°a cÃ³ bÃ\xa0i táº\xadp nÃ\xa0o sáºµn sÃ\xa0ng.': 'Chưa có bài tập nào sẵn sàng.',

    'Tiáº¿n Ä‘á»™': 'Tiến độ',
    'hoáº¡t Ä‘á»™ng Ä‘Ã£ lÃ\xa0m': 'hoạt động đã làm',
    'Ä iá»ƒm hiá»‡n táº¡i': 'Điểm hiện tại',
    'Ä ang má»Ÿ': 'đang mở',
    'Tráº¡ng thÃ¡i': 'Trạng thái',
    'Ä á»§ Ä‘iá» u kiá»‡n Ä‘á»ƒ hoÃ\xa0n thÃ\xa0nh bÃ\xa0i.': 'Đủ điều kiện để hoàn thành bài.',
    'LÃ\xa0m tiáº¿p tá»«ng bÆ°á»›c Ä‘á»ƒ má»Ÿ khÃ³a pháº§n thÆ°á»Ÿng.': 'Làm tiếp từng bước để mở khóa phần thưởng.',

    'KÃ©o xuá»‘ng Ä‘á»ƒ lÃ\xa0m bÃ\xa0i': 'Kéo xuống để làm bài',
    'Tá»«ng bÆ°á»›c má»™t': 'Từng bước một',
    'Má»—i tháº» lÃ\xa0 má»™t bÆ°á»›c riÃªng, lÃ\xa0m xong bÆ°á»›c nÃ\xa0y rá»“i tiáº¿p tá»¥c vuá»‘t xuá»‘ng bÆ°á»›c tiáº¿p theo.': 'Mỗi thẻ là một bước riêng, làm xong bước này rồi tiếp tục vuốt xuống bước tiếp theo.',
    'bÆ°á»›c': 'bước',
    'BÆ°á»›c': 'Bước',

    'Xong rá»“i': 'Xong rồi',
    'Ä ang chá»  em lÃ\xa0m': 'Đang chờ em làm',
    'Hoáº¡t Ä‘á»™ng há» c táº\xadp': 'Hoạt động học tập',
    'BÃ\xa0i há» c nÃ\xa0y chÆ°a cÃ³ hoáº¡t Ä‘á»™ng nÃ\xa0o.': 'Bài học này chưa có hoạt động nào.',
    'hoáº¡t Ä‘á»™ng': 'hoạt động',
    'Hoáº¡t Ä‘á»™ng': 'Hoạt động',

    'Ä ang báº¯t Ä‘áº§u...': 'Đang bắt đầu...',
    'LÃ\xa0m láº¡i tá»« Ä‘áº§u': 'Làm lại từ đầu',
    'Báº¯t Ä‘áº§u bÃ\xa0i há» c': 'Bắt đầu bài học',
    'Ä ang hoÃ\xa0n thÃ\xa0nh...': 'Đang hoàn thành...',
    'HoÃ\xa0n thÃ\xa0nh bÃ\xa0i': 'Hoàn thành bài',
    'Chá» n bÃ\xa0i khÃ¡c': 'Chọn bài khác',
    'Cháº¡m vÃ\xa0o má»™t tháº» bÃ\xa0i á»Ÿ phÃ\xada trÃªn Ä‘á»ƒ báº¯t Ä‘áº§u.': 'Chạm vào một thẻ bài ở phía trên để bắt đầu.',
    'Khi má»Ÿ bÃ\xa0i, toÃ\xa0n bá»™ hoáº¡t Ä‘á»™ng sáº½ hiá»‡n theo chiá» u dá» c Ä‘á»ƒ em chá»‰ viá»‡c kÃ©o xuá»‘ng vÃ\xa0 lÃ\xa0m láº§n lÆ°á»£t.': 'Khi mở bài, toàn bộ hoạt động sẽ hiện theo chiều dọc để em chỉ việc kéo xuống và làm lần lượt.',

    'VÃ\xa0o lá»›p': 'Vào lớp',
    'Tham gia lá»›p má»›i': 'Tham gia lớp mới',
    'ID lá»›p': 'ID lớp',
    'VÃ\xad dá»\xa5:': 'Ví dụ:',
    'Máº\xadt kháº©u vÃ\xa0o lá»›p': 'Mật khẩu vào lớp',
    'Ä ang vÃ\xa0o lá»›p...': 'Đang vào lớp...',
    'VÃ\xa0o lá»›p ngay': 'Vào lớp ngay',
    'Em Ä‘ang há» c á»Ÿ:': 'Em đang học ở:',
    'lá»›p': 'lớp',
    'Lá»›p': 'Lớp',

    'NgÆ°á» i há»— trá»£': 'Người hỗ trợ',
    'GiÃ¡o viÃªn cá»§a em': 'Giáo viên của em',
    'ChÆ°a cáº\xadp nháº\xadt trÆ°á» ng': 'Chưa cập nhật trường',
    'trÆ°á» ng': 'trường',
    'ChÆ°a cÃ³ thÃ´ng tin liÃªn há»‡': 'Chưa có thông tin liên hệ',
    'liÃªn há»‡': 'liên hệ',
    'Em chÆ°a liÃªn káº¿t vá»›i giÃ¡o viÃªn nÃ\xa0o.': 'Em chưa liên kết với giáo viên nào.',
    'liÃªn káº¿t': 'liên kết',

    'KhÃ´ng gian há» c sinh': 'Không gian học sinh',
    'HÃ´m nay em há» c gÃ¬?': 'Hôm nay em học gì?',
    'Má» i bÃ\xa0i Ä‘Æ°á»£c giao, hoáº¡t Ä‘á»™ng há» c táº\xadp vÃ\xa0 tiáº¿n Ä‘á»™ Ä‘á» u náº±m trong cÃ¹ng má»™t khu vá»±c Ä‘á»ƒ em thao tÃ¡c nhanh hÆ¡n vÃ\xa0 dá»… theo dÃµi hÆ¡n.': 'Mọi bài được giao, hoạt động học tập và tiến độ đều nằm trong cùng một khu vực để em thao tác nhanh hơn và dễ theo dõi hơn.',
    'HoÃ\xa0n thÃ\xa0nh bÃ\xa0i há» c': 'Hoàn thành bài học',
    'Em Ä‘Ã£ hoÃ\xa0n thÃ\xa0nh bÃ\xa0i há» c nÃ\xa0y vÃ\xa0 Ä‘Ã£ quay vá»  trang chá»§ Ä‘á»ƒ chá» n bÃ\xa0i tiáº¿p theo.': 'Em đã hoàn thành bài học này và đã quay về trang chủ để chọn bài tiếp theo.',

    'Tá»•ng bÃ\xa0i táº\xadp': 'Tổng bài tập',
    'Ä ang há» c': 'Đang học',
    'Ä Ã£ xong': 'Đã xong',
    'sá»‘': 'số',
    'Sá»‘ giÃ¡o viÃªn': 'Số giáo viên',

    'ThÃ´ng tin há» c sinh': 'Thông tin học sinh',
    'Há» c sinh': 'Học sinh',
    'há» c sinh': 'học sinh',
    'Má»©c Ä‘á»™:': 'Mức độ:',
    'chÆ°a rÃµ': 'chưa rõ',
    'Ghi chÃº há»— trá»£:': 'Ghi chú hỗ trợ:',
    'ChÆ°a cÃ³ ghi chÃº há»— trá»£.': 'Chưa có ghi chú hỗ trợ.',
    'ghi chÃº': 'ghi chú',
    'há»— trá»£': 'hỗ trợ',
    'GiÃ¡o viÃªn Ä‘ang dáº¡y em': 'Giáo viên đang dạy em',
    'Sá»‘ Ä‘iá»‡n thoáº¡i:': 'Số điện thoại:',
    'ChÆ°a cáº\xadp nháº\xadt': 'Chưa cập nhật',
    'cáº\xadp nháº\xadt': 'cập nhật',
    'Sá»‘ lá»›p Ä‘ang há» c vá»›i giÃ¡o viÃªn nÃ\xa0y:': 'Số lớp đang học với giáo viên này:',

    'Tham gia lá»›p há» c': 'Tham gia lớp học',
    'Danh sÃ¡ch lá»›p hiá»‡n táº¡i:': 'Danh sách lớp hiện tại:',
    'danh sÃ¡ch': 'danh sách',
    'Danh sÃ¡ch': 'Danh sách',
    'hiá»‡n táº¡i': 'hiện tại',
    'Em chÆ°a tham gia lá»›p há» c nÃ\xa0o.': 'Em chưa tham gia lớp học nào.',

    'BÃ\xa0i gáº§n nháº¥t': 'Bài gần nhất',
    'gáº§n nháº¥t': 'gần nhất',
    'Tráº¡ng thÃ¡i sáºµn sÃ\xa0ng:': 'Trạng thái sẵn sàng:',
    'sáºµn sÃ\xa0ng': 'sẵn sàng',
    'ChÆ°a cÃ³ bÃ\xa0i há» c nÃ\xa0o Ä‘Æ°á»£c giao cho tÃ\xa0i khoáº£n nÃ\xa0y.': 'Chưa có bài học nào được giao cho tài khoản này.',

    'Ä iá» u hÆ°á»›ng há» c táº\xadp': 'Điều hướng học tập',
    'Ä iá» u hÆ°á»›ng': 'Điều hướng',
    'Danh sÃ¡ch bÃ\xa0i Ä‘Æ°á»£c giao': 'Danh sách bài được giao',
    'Ä‘Æ°á»£c giao': 'được giao',
    'Chá» n bÃ\xa0i á»Ÿ cá»™t nÃ\xa0y, khu vá»±c bÃªn pháº£i sáº½ hiá»ƒn thá»‹ Ä‘áº§y Ä‘á»§ ná»™i dung vÃ\xa0 hoáº¡t Ä‘á»™ng há» c táº\xadp.': 'Chọn bài ở cột này, khu vực bên phải sẽ hiển thị đầy đủ nội dung và hoạt động học tập.',
    'Ä‘áº§y Ä‘á»§': 'đầy đủ',
    'ná»™i dung': 'nội dung',

    'ChÆ°a cÃ³ mÃ´n há» c': 'Chưa có môn học',
    'mÃ´n há» c': 'môn học',
    'ChÆ°a cÃ³ bÃ\xa0i táº\xadp nÃ\xa0o.': 'Chưa có bài tập nào.',

    'Khu vá»±c lÃ\xa0m bÃ\xa0i': 'Khu vực làm bài',
    'Chi tiáº¿t bÃ\xa0i há» c': 'Chi tiết bài học',
    'Chi tiáº¿t': 'Chi tiết',
    'Pháº§n nÃ\xa0y Ä‘Æ°á»£c Æ°u tiÃªn diá»‡n tÃ\xadch lá»›n hÆ¡n Ä‘á»ƒ em thao tÃ¡c thoáº£i mÃ¡i khi lÃ\xa0m cÃ¡c hoáº¡t Ä‘á»™ng.': 'Phần này được ưu tiên diện tích lớn hơn để em thao tác thoải mái khi làm các hoạt động.',
    'thoáº£i mÃ¡i': 'thoải mái',
    'ChÆ°a chá» n bÃ\xa0i': 'Chưa chọn bài',
    'BÃ\xa0i Ä‘ang má»Ÿ': 'Bài đang mở',
    'ChÆ°a cÃ³ mÃ´ táº£ bÃ\xa0i há» c.': 'Chưa có mô tả bài học.',
    'mÃ´ táº£': 'mô tả',

    'Ä iá»ƒm sá»‘': 'Điểm số',

    'Hoáº¡t Ä‘á»™ng trong bÃ\xa0i': 'Hoạt động trong bài',
    'hoáº¡t Ä‘á»™ng Ä‘ang sáºµn sÃ\xa0ng cho em luyá»‡n táº\xadp.': 'hoạt động đang sẵn sàng cho em luyện tập.',
    'luyá»‡n táº\xadp': 'luyện tập',

    'Thao tÃ¡c há» c bÃ\xa0i': 'Thao tác học bài',
    'Thao tÃ¡c': 'Thao tác',
    'Em chá»‰ cáº§n báº¯t Ä‘áº§u bÃ\xa0i, lÃ\xa0m cÃ¡c hoáº¡t Ä‘á»™ng vÃ\xa0 báº¥m hoÃ\xa0n thÃ\xa0nh khi Ä‘Ã£ xong háº¿t.': 'Em chỉ cần bắt đầu bài, làm các hoạt động và bấm hoàn thành khi đã xong hết.',
    'Ä Ã¡nh dáº¥u Ä‘Ã£ hoÃ\xa0n thÃ\xa0nh': 'Đánh dấu đã hoàn thành',
    'Ä Ã¡nh dáº¥u': 'Đánh dấu',
    'Quay vá»  trang chá»§': 'Quay về trang chủ',
    'trang chá»§': 'trang chủ',

    'Tiáº¿n Ä‘á»™ tá»± Ä‘á»™ng': 'Tiến độ tự động',
    'tá»± Ä‘á»™ng': 'tự động',
    'Há»‡ thá»‘ng tá»± cáº\xadp nháº\xadt theo sá»‘ hoáº¡t Ä‘á»™ng em Ä‘Ã£ lÃ\xa0m, em khÃ´ng cáº§n nháº\xadp tay ná»¯a.': 'Hệ thống tự cập nhật theo số hoạt động em đã làm, em không cần nhập tay nữa.',
    'Tiáº¿n Ä‘á»™ hiá»‡n táº¡i': 'Tiến độ hiện tại',
    'Táº¥t cáº£ hoáº¡t Ä‘á»™ng Ä‘Ã£ xong, em cÃ³ thá»ƒ báº¥m hoÃ\xa0n thÃ\xa0nh bÃ\xa0i há» c.': 'Tất cả hoạt động đã xong, em có thể bấm hoàn thành bài học.',
    'Táº¥t cáº£': 'Tất cả',
    'Em cÃ²n ': 'Em còn ',
    ' hoáº¡t Ä‘á»™ng chÆ°a hoÃ\xa0n táº¥t.': ' hoạt động chưa hoàn tất.',
    'hoÃ\xa0n táº¥t': 'hoàn tất',
    'Chá» n má»™t bÃ\xa0i há» c Ä‘á»ƒ báº¯t Ä‘áº§u.': 'Chọn một bài học để bắt đầu.',
    'Danh sÃ¡ch bÃ\xa0i táº\xadp náº±m á»Ÿ cá»™t bÃªn trÃ¡i. Khi em chá» n bÃ\xa0i, toÃ\xa0n bá»™ hoáº¡t Ä‘á»™ng vÃ\xa0 tráº¡ng thÃ¡i há» c sáº½ hiá»‡n táº¡i Ä‘Ã¢y.': 'Danh sách bài tập nằm ở cột bên trái. Khi em chọn bài, toàn bộ hoạt động và trạng thái học sẽ hiện tại đây.',

    'KhÃ´ng gian': 'Không gian',
    'Ä‘Æ°á»£c lÃ\xa0m': 'được làm',
    'cá»™t bÃªn trÃ¡i': 'cột bên trái',
    'hiá»‡n táº¡i Ä‘Ã¢y': 'hiện tại đây',
    'Ä‘áº§y Ä‘á»§': 'đầy đủ',
    'â€¢': '•',

    'áº£': 'ả', 'Ã´': 'ô', 'hÃ¬nh': 'hình', 'Ä‘Ã¡p': 'đáp', 'Ã¡n': 'án', 'NhÃ¬n': 'Nhìn', 'rá»“i': 'rồi',
    'Ná»‘i': 'Nối', 'Ä‘Ãºng': 'đúng', 'KÃ©o': 'Kéo', 'vÃ\xa0': 'và', 'tháº£': 'thả', 'Nghe': 'Nghe',
    'chá» n': 'chọn', 'Chá» n': 'Chọn', 'Xem': 'Xem', 'tráº£': 'trả', 'lá» i': 'lời', 'LÃ\xa0m': 'Làm',
    'tá»«ng': 'từng', 'bÆ°á»›c': 'bước', 'BÆ°á»›c': 'Bước', 'tháº»': 'thẻ', 'TÃ¬nh': 'Tình',
    'huá»‘ng': 'huống', 'TrÃ²': 'Trò', 'chuyá»‡n': 'chuyện', 'BÃ\xa0i': 'Bài', 'bÃ\xa0i': 'bài',
    'há» c': 'học', 'MÃ\xa0n': 'Màn', 'KhÃ´ng': 'Không', 'gian': 'gian', 'trá»±c': 'trực',
    'quan': 'quan', 'HÃ´m': 'Hôm', 'nay': 'nay', 'mÃ¬nh': 'mình', 'nÃ\xa0o': 'nào',
    'Ä‘Æ°á»£c': 'được', 'lÃ\xa0m': 'làm', 'theo': 'theo', 'kiá»ƒu': 'kiểu', 'cuá»™n': 'cuộn',
    'dá» c': 'dọc', 'nÃºt': 'nút', 'to': 'to', 'lá»›n': 'lớn', 'Ä‘á»ƒ': 'để', 'em': 'em',
    'chá»‰': 'chỉ', 'viá»‡c': 'việc', 'nhÃ¬n': 'nhìn', 'cháº¡m': 'chạm', 'xuá»‘ng': 'xuống',
    'tiáº¿p': 'tiếp', 'tá»¥c': 'tục', 'Ä‘Ã£': 'đã', 'xong': 'xong', 'giÃ¡o': 'giáo',
    'viÃªn': 'viên', 'HoÃ\xa0n': 'Hoàn', 'thÃ\xa0nh': 'thành', 'Giá» i': 'Giỏi', 'láº¯m': 'lắm',
    'cÃ³': 'có', 'thá»ƒ': 'thể', 'cá»§a': 'của', 'bÃªn': 'bên', 'dÆ°á»›i': 'dưới', 'má»Ÿ': 'mở',
    'giao': 'giao', 'táº\xadp': 'tập', 'Ä iá»ƒm': 'Điểm', 'ChÆ°a': 'Chưa', 'sáºµn': 'sẵn',
    'sÃ\xa0ng': 'sàng', 'Tiáº¿n': 'Tiến', 'Ä‘á»™': 'độ', 'hoáº¡t': 'hoạt', 'Ä‘á»™ng': 'động',
    'hiá»‡n': 'hiện', 'táº¡i': 'tại', 'Tráº¡ng': 'Trạng', 'thÃ¡i': 'thái', 'Ä á»§': 'Đủ',
    'Ä‘iá» u': 'điều', 'kiá»‡n': 'kiện', 'khÃ³a': 'khóa', 'pháº§n': 'phần', 'thÆ°á»Ÿng': 'thưởng',
    'Má»—i': 'Mỗi', 'lÃ\xa0': 'là', 'má»™t': 'một', 'riÃªng': 'riêng', 'vuá»‘t': 'vuốt',
    'chá» ': 'chờ', 'nÃ\xa0y': 'này', 'báº¯t': 'bắt', 'Ä‘áº§u': 'đầu', 'láº¡i': 'lại',
    'tá»«': 'từ', 'khÃ¡c': 'khác', 'phÃ\xada': 'phía', 'trÃªn': 'trên', 'Khi': 'Khi',
    'toÃ\xa0n': 'toàn', 'bá»™': 'bộ', 'sáº½': 'sẽ', 'chiá» u': 'chiều', 'láº§n': 'lần',
    'lÆ°á»£t': 'lượt', 'VÃ\xa0o': 'Vào', 'lá»›p': 'lớp', 'Tham': 'Tham', 'gia': 'gia',
    'má»›i': 'mới', 'VÃ\xad': 'Ví', 'dá»\xa5': 'dụ', 'Máº\xadt': 'Mật', 'kháº©u': 'khẩu', 'ngay': 'ngay',
    'NgÆ°á» i': 'Người', 'há»—': 'hỗ', 'trá»£': 'trợ', 'cáº\xadp': 'cập', 'nháº\xadt': 'nhật',
    'trÆ°á» ng': 'trường', 'thÃ´ng': 'thông', 'tin': 'tin', 'liÃªn': 'liên', 'há»‡': 'hệ',
    'káº¿t': 'kết', 'vá»›i': 'với', 'gÃ¬': 'gì', 'Má» i': 'Mọi', 'Ä‘á» u': 'đều',
    'náº±m': 'nằm', 'trong': 'trong', 'cÃ¹ng': 'cùng', 'khu': 'khu', 'vá»±c': 'vực',
    'thao': 'thao', 'tÃ¡c': 'tác', 'nhanh': 'nhanh', 'hÆ¡n': 'hơn', 'dá»…': 'dễ',
    'dÃµi': 'dõi', 'quay': 'quay', 'vá» ': 'về', 'Tá»•ng': 'Tổng', 'Sá»‘': 'Số',
    'sá»‘': 'số', 'Má»©c': 'Mức', 'rÃµ': 'rõ', 'Ghi': 'Ghi', 'chÃº': 'chú', 'Ä‘ang': 'đang',
    'dáº¡y': 'dạy', 'Ä‘iá»‡n': 'điện', 'thoáº¡i': 'thoại', 'danh': 'danh', 'sÃ¡ch': 'sách',
    'gáº§n': 'gần', 'nháº¥t': 'nhất', 'cho': 'cho', 'tÃ\xa0i': 'tài', 'khoáº£n': 'khoản',
    'Ä iá» u': 'Điều', 'hÆ°á»›ng': 'hướng', 'á»Ÿ': 'ở', 'cá»™t': 'cột', 'pháº£i': 'phải',
    'hiá»ƒn': 'hiển', 'thá»‹': 'thị', 'Ä‘áº§y': 'đầy', 'Ä‘á»§': 'đủ', 'ná»™i': 'nội',
    'dung': 'dung', 'mÃ´n': 'môn', 'Chi': 'Chi', 'tiáº¿t': 'tiết', 'Pháº§n': 'Phần',
    'Æ°u': 'ưu', 'tiÃªn': 'tiên', 'diá»‡n': 'diện', 'tÃ\xadch': 'tích', 'thoáº£i': 'thoải',
    'mÃ¡i': 'mái', 'mÃ´': 'mô', 'táº£': 'tả', 'luyá»‡n': 'luyện', 'Thao': 'Thao',
    'háº¿t': 'hết', 'Ä Ã¡nh': 'Đánh', 'dáº¥u': 'dấu', 'Quay': 'Quay', 'trang': 'trang',
    'chá»§': 'chủ', 'tá»±': 'tự', 'Há»‡': 'Hệ', 'thá»‘ng': 'thống', 'nháº\xadp': 'nhập',
    'tay': 'tay', 'ná»¯a': 'nữa', 'Táº¥t': 'Tất', 'cáº£': 'cả', 'cÃ²n': 'còn', 'táº¥t': 'tất',
    'khÃ³': 'khó', 'nÃ¢ng': 'nâng', 'phÃ¹': 'phù', 'há»£p': 'hợp', 'Cáº§n': 'Cần',
    'yÃªu': 'yêu', 'cáº§u': 'cầu', 'Ä Ã\xa0ng': 'Đàng', 'Ä‘Ã³': 'đó',
}

sorted_replacements = sorted(replacements.items(), key=lambda x: len(x[0]), reverse=True)

for old_str, new_str in sorted_replacements:
    content = content.replace(old_str, new_str)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print('File replaced using Python.')
